language: node_js

node_js:
  - "11.1.0"

env:
  - HEXO_CACHE_DIR=$HOME/hexo

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/hexo

before_install:
  - export TZ='Asia/Shanghai'
  - find $HEXO_CACHE_DIR -name \*.json -exec cp {} ./ \;

install:
  - yarn install
  - yarn global add gulp
  - git clone https://github.com/polarlights/hexo-theme-next themes/next
  - git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox
  - git clone https://github.com/theme-next/theme-next-fastclick themes/next/source/lib/fastclick
  - git clone https://github.com/theme-next/theme-next-jquery-lazyload themes/next/source/lib/jquery_lazyload

script:
  - node_modules/hexo/bin/hexo generate
  - cp ./db.json $HEXO_CACHE_DIR/db.json

after_success:
  - sed -i "s/LEANCLOUD_USER/${LEANCLOUD_USER}/" _config.yml
  - sed -i "s/LEANCLOUD_PASSWORD/${LEANCLOUD_PASSWORD}/" _config.yml
  - node_modules/hexo/bin/hexo deploy

branches:
  only:
    - source

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target-branch: master
  on:
    branch: source
